name: BinapiX Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the release'
        required: false
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        #sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Set up CMake
      run: |
        sudo apt-get install -y cmake

    - name: Configure CMake
      run: cmake -S . -B build -DBOOST_ROOT=/usr

    - name: Build
      run: cmake --build build -j $(nproc)

 #   - name: Run tests#，未来增加测试
 #     run: cmake --build build --target test

      # Add your build steps here

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            Release notes for ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/
          asset_name: binapi
          asset_content_type: application/octet-stream
