name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Set up CMake
      uses: cmake/experimental-action@v1

    - name: Configure CMake
      run: cmake -S . -B build -DBOOST_ROOT=/usr

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cmake --build build --target test
